<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Activo',
    'All' => 'Todo',
    'Error saving the record {title}' => 'Error guardando el registro {title}',
    'From \'{from}\' or until \'{until}\' dates are in invalid date format' => 'Las fechas desde: \'{from}\' o hasta: \'{until}\' no tienen un formato válido',
    '{from-label} {from} can\'t be greater than {until-label} {until}'
     => '{from-label}: \'{from}\' no puede ser posterior a {until-label}: \'{until}\'',
    'Inactive' => 'Inactivo',
    'The {attribute} \'{value}\' is not valid' => 'El valor \'{value}\' del campo \'{attribute}\' no es válido',
    '{La} {title} <strong>{record}</strong> has been successfully created.' => '{La} {title} <strong>{record}</strong> se ha creado correctamente.',
    '{La} {title} <strong>{record}</strong> has been successfully deleted.' => '{La} {title} <strong>{record}</strong> se ha borrado correctamente.',
    '{La} {title} <strong>{record}</strong> has been successfully duplicated.' => '{La} {title} <strong>{record}</strong> se ha duplicado correctamente.',
    '{La} {title} <strong>{record}</strong> has been successfully updated.' => '{La} {title} <strong>{record}</strong> se ha actualizado correctamente.',
    '{Title_plural}' => '{Title_plural}',
    '{inactive} since' => '{inactive} desde',
];
